DROP DATABASE  `tittineShare`;
CREATE DATABASE `tittineShare`;

CREATE TABLE  `tittineShare`.`UTILISATEUR` (
  `UTILISATEUR_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `UTILISATEUR_NOM` VARCHAR(20) NOT NULL,
  `UTILISATEUR_PRENOM` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`UTILISATEUR_ID`) USING BTREE,
  INDEX `IDX_UTILISATEUR_ID` (`UTILISATEUR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE  `tittineShare`.`TRAJET` (
  `TRAJET_ID`		INT(10) NOT NULL AUTO_INCREMENT,
  `UTILISATEUR_ID` 	INT(10) NOT NULL,
  `VILLE_DEPART` 	VARCHAR(20) NOT NULL,
  `VILLE_ARRIVEE` 	VARCHAR(20) NOT NULL,
  `DEPART_MINUTE` 	INT(2) NOT NULL,
  `ARRIVE_EMINUTE` 	INT(2) NOT NULL,
  `DEPART_HEURE`  	INT(2) NOT NULL,
  `ARRIVEE_HEURE`  	INT(2) NOT NULL,
  `DATE_TRAJET` 	VARCHAR(20) NOT NULL,
  `VEHICULE`	 	VARCHAR(20),
  `LIEU_DEPART` 	VARCHAR(100),
  `LIEU_ARRIVEE` 	VARCHAR(100),
  `DESCRIPTION` 	VARCHAR(500),
  `NB_PASSAGERS`  	INT(2),
  PRIMARY KEY (`TRAJET_ID`) USING BTREE,
  CONSTRAINT FOREIGN KEY (`UTILISATEUR_ID`) 
        REFERENCES `tittineShare`.`UTILISATEUR`(`UTILISATEUR_ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;